### ISSUE TITLE
"Missing" status after trying to uninstall

### ISSUE THREAD

**Issue by michaeldavidtodd** [Frontwise/craft-404monitor#6]
We're not using this plugin anymore. If I try to uninstall and remove it, it just ends up sticking around with a status of "Missing". What's odd is that sometimes it shows up and other times it doesn't. I can't find any remaining references to it anywhere in my code base or in the database. Do you know what causes this? Even if I reinstall it and uninstall again, it does the same thing.

**Comment by RichardJong** [comment]
Thanks for the feedback!
Is it still present in composer.json or in your yaml config?

**Comment by michaeldavidtodd** [comment]
Sorry for disappearing! No, I don't see it in composer.json or the yaml config files. I'm having a hard time finding any trace of it. But I'm also not sure exactly what to look for other than "404" and "monitor".

**Comment by RichardJong** [comment]
It should be listed as 'frontwise/craft-monitor404' in your composer.json when installed.
